name: sticky_notes
description: 간단한 노트 애플리케이션
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^1.0.1
  sqflite: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
